### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by c1a1o1** [CODEJIN/PVCGAN_Torch#3]
[Evaluation]:   0%|          | 0/24 [00:00<?, ?it/s]F:\ProgramData\Anaconda3\lib\site-packages\torch\functional.py:516: UserWarning: stft will require the return_complex parameter be explicitly  specified in a future PyTorch release. Use return_complex=False  to preserve the current behavior or return_complex=True to return  a complex output. (Triggered internally at  ..\aten\src\ATen\native\SpectralOps.cpp:653.)
  normalized, onesided, return_complex)
[Evaluation]:   0%|          | 0/24 [13:16<?, ?it/s]
Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "F:/work/PVCGAN_Torch-master/Train.py", line 264, in Evaluation_Step
    loss_Dict['Generator/Spectral_Convergence'], loss_Dict['Generator/Magnitude'] = self.criterion_Dict['STFT'](fakes, audios)
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\work\PVCGAN_Torch-master\Modules.py", line 595, in forward
    new_Spectral_Convergence_Loss, new_Magnitude_Loss = layer(x, y)
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\work\PVCGAN_Torch-master\Modules.py", line 619, in forward
    x_Magnitute = self.STFT(x)
  File "F:\work\PVCGAN_Torch-master\Modules.py", line 633, in STFT
    window= self.window(self.win_length)
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\functional.py", line 516, in stft
    normalized, onesided, return_complex)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by CODEJIN** [comment]
Hi, c1a1o1,


When I tested both of GPU and CPU environments, but there was no error. 

![image](https://user-images.githubusercontent.com/17133841/99916661-c32ae780-2d4e-11eb-94d8-c5f4cddffa27.png)

I want to know that which PyTorch version use. I tested this code at 1.4, 1.5, and 1.6. If your version is lower than, please check it.


Thanks,

Heejo

**Comment by c1a1o1** [comment]
Thanks  for your help!

**Comment by CODEJIN** [comment]
To @c1a1o1 

Hi, after that, I upgrade torch version 1.7.0, and I faced the same problem. I found the problem occurs when `torch.stft` function is called because of `window` paramter. I fixed it and it worked when I tested. If you have time, please check it.

Thanks,

Heejo

**Comment by c1a1o1** [comment]
@CODEJIN  Thanks a lot!
